title: "Nguenang Njinang Edwige Prisca"
logo: img/Mein Profilbild.jpg
description: "Portfolio Informatik Studium mit Vertiefung in Data Science"
show_downloads: true
theme: jekyll-theme-minimal
lang: de
